version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
      time: "03:00"
    labels:
      - "PR • MAINTENANCE"
    assignees:
      - "andyone"
    reviewers:
      - "andyone"
    groups:
      all:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2/feature/s3/manager"
      - dependency-name: "github.com/aws/aws-sdk-go-v2/feature/s3"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
      time: "03:00"
    labels:
      - "PR • MAINTENANCE"
    assignees:
      - "andyone"
    reviewers:
      - "andyone"
